//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitor.Resource {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Seguranca {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Seguranca() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceMonitor.Resource.Seguranca", typeof(Seguranca).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///US.CODIGO AS CODIGO,
        ///PESSOA,
        ///LOGIN,
        ///SENHA,
        ///CASE WHEN US.TIPO = &apos;I&apos; THEN &apos;INTERNO&apos; ELSE &apos;EXTERNO&apos; END AS TIPO,
        ///DOMINIO,
        ///EMAIL,
        ///RECUPEROU_SENHA,
        ///STATUS,
        ///UPPER(PS.NOME) AS NOME,
        ///ps.cpf_cnpj as Cpf,
        ///PS.celular as Celular,
        ///coalesce (convert(varchar(10),PS.nasc_criacao,103) , &apos;&apos;) as DataNascimento
        ///FROM M0.USUARIO	US
        ///JOIN M0.PESSOA	PS ON PS.CODIGO = US.PESSOA
        ///WHERE 
        ///1=1
        ///AND LOGIN = @LOGIN
        ///AND STATUS = &apos;A&apos;.
        /// </summary>
        internal static string BuscarDadosUsuario {
            get {
                return ResourceManager.GetString("BuscarDadosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT TOP 1 
        ///LO.*,
        ///coalesce (convert(varchar(10),PE.DataNascimento ,103) , &apos;&apos;) as DataNascimento,
        ///PE.Cnp     AS cnp, 
        ///EP.Email   AS email, 
        ///CAST(TP.DDD AS VARCHAR) + CAST(TP.Numero AS VARCHAR) AS celular
        ///FROM Site.adm.Login                   LO WITH (NOLOCK)
        ///LEFT JOIN Cardio.dbo.PrestadorServico PS WITH (NOLOCK) ON PS.CodigoReduzido = CASt(LO.Usuario AS BIGINT )
        ///JOIN Cardio.dbo.Pessoa           PE WITH (NOLOCK) ON PS.Pessoa = PE.AutoId AND PS.Classe = 101 AND PE.AutoId IS NOT NULL
        ///LEFT JOIN Cardio [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string BuscarDadosUsuarioCooperado {
            get {
                return ResourceManager.GetString("BuscarDadosUsuarioCooperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///CODIGO AS LoginWebCodigo,
        ///CPF AS LoginWebCPF,
        ///EMAIL AS LoginWebEmail,
        ///coalesce (convert(varchar(10),DT_NASCIMENTO,103) , &apos;&apos;) as LoginWebDataNascimento,
        ///NOME AS LoginWebNome,
        ///TELEFONE AS LoginWebTelefone,
        ///SENHA AS LoginWebSenha,
        ///CONFIRMACAO_CADASTRO AS LoginWebConfirmacao_Cadastro,
        ///DT_CANCELAMENTO AS LoginWebDt_Cancelamento,
        ///USUARIO_CANCELAMENTO AS UsuarioCodigo,
        ///USUARIO_VENDEDOR AS UsuarioCodigoVendedor,
        ///case when USUARIO_VENDEDOR is null then &apos;CLIENTE&apos; else &apos;VENDEDOR&apos; end as TipoUsuario [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string BuscarDadosUsuarioLogin {
            get {
                return ResourceManager.GetString("BuscarDadosUsuarioLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXEC [MP].[CreditCardRedeLog].
        /// </summary>
        internal static string CreditCardLog {
            get {
                return ResourceManager.GetString("CreditCardLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a exec [WS].[EmailLog].
        /// </summary>
        internal static string EmailLog {
            get {
                return ResourceManager.GetString("EmailLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT [Codigo]
        ///      ,[Servidor]
        ///      ,[Porta]
        ///      ,[Seguranca]
        ///      ,[Usuario]
        ///      ,[Senha]
        ///      ,[OrigemEmail] as Remetente
        ///      ,[OrigemEmailNome]
        ///      ,[Cc]
        ///  FROM [M0].[EmailServidor]
        ///WHERE [Codigo] = @servidor.
        /// </summary>
        internal static string EmailServidor {
            get {
                return ResourceManager.GetString("EmailServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT
        ///RE.CODIGO		 AS RecursoCodigo,
        ///RE.DESCRICAO	 AS RecursoRotulo,
        ///ME.Nome			 AS RecursoNome,
        ///RE.Icone		 AS RecursoIcone,
        ///RE.tipo			 AS RecursoTipo,
        ///
        ///RE.modulo		 AS ModuloCodigo,
        ///MO.descricao	 AS ModuloRotulo,
        ///MO.nome          AS ModuloNome,
        ///MO.icone		 AS ModuloIcone,
        ///
        ///SE.Codigo as Servico,
        ///--TSE.Url+Rota as ServicoUrl,
        ///Rota as ServicoUrl,
        ///TSE.TIPO_EXIBICAO AS ServicoTipoExibicao,
        ///RE.recurso_pai as RecursoPai,
        ///case when (select count(codigo) from m0.recurso sub where sub.recurso_ [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ListarModulosMenuFavoritosPorUsuario {
            get {
                return ResourceManager.GetString("ListarModulosMenuFavoritosPorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT
        ///RE.Ordem		 AS Ordem,
        ///RE.CODIGO		 AS RecursoCodigo,
        ///RE.DESCRICAO	 AS RecursoRotulo,
        ///RE.Nome			 AS RecursoNome,
        ///RE.Icone		 AS RecursoIcone,
        ///RE.tipo			 AS RecursoTipo,
        ///
        ///RE.modulo		 AS ModuloCodigo,
        ///MO.descricao	 AS ModuloRotulo,
        ///MO.nome          AS ModuloNome,
        ///MO.icone		 AS ModuloIcone,
        ///
        ///SE.Codigo as Servico,
        ///--TSE.Url+Rota as ServicoUrl,
        ///Rota as ServicoUrl,
        ///TSE.TIPO_EXIBICAO AS ServicoTipoExibicao,
        ///RE.recurso_pai as RecursoPai,
        ///case when (select count(codigo) from m0.recurso  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ListarModulosMenuPorUsuario {
            get {
                return ResourceManager.GetString("ListarModulosMenuPorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT
        ///RE.Nome AS Rotulo,
        ///coalesce(RE.ICONE, &apos;&apos;) AS Icone,
        ///RE.NOME AS Modulo,
        ///RE.codigo AS Codigo,
        ///&apos;/SynergiusServicos/M0/api/ws/listarmenu&apos; as ServicoUrl,
        ///RE.descricao as Descricao
        ///
        ///FROM M0.Usuario			US
        ///JOIN M0.Pessoa			PE	ON PE.CODIGO = US.PESSOA
        ///JOIN M0.Usuario_Perfil	UP	ON US.CODIGO = UP.USUARIO 
        ///JOIN M0.Perfil			PF	ON PF.codigo = UP.perfil 
        ///JOIN M0.Perfil_Recurso  PR	ON PR.perfil = PF.codigo
        ///JOIN M0.Recurso			RE	ON RE.codigo = PR.recurso
        ///
        ///WHERE 1=1
        ///AND UPPER(LOGIN) = @LOGIN
        ///AN [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ListarModulosPorUsuario {
            get {
                return ResourceManager.GetString("ListarModulosPorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select top 1 PathServidorArquivos from M0.Server where [url] = @url.
        /// </summary>
        internal static string PathServidorArquivos {
            get {
                return ResourceManager.GetString("PathServidorArquivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a exec [WS].[ServicoLog] .
        /// </summary>
        internal static string ServicoLog {
            get {
                return ResourceManager.GetString("ServicoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a exec [WS].[SMSLog].
        /// </summary>
        internal static string SMSLog {
            get {
                return ResourceManager.GetString("SMSLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a exec SM.TarefaExecucaoLog.
        /// </summary>
        internal static string TarefaExecucaoLog {
            get {
                return ResourceManager.GetString("TarefaExecucaoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string UpdateBoletoCardio {
            get {
                return ResourceManager.GetString("UpdateBoletoCardio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE m1.dados_boleto
        ///SET situacao = &apos;{0}&apos;, 
        ///motivo = &apos;{1}&apos;, 
        ///datapagamento = &apos;{2}&apos;
        ///WHERE 1 = 1
        ///AND codigo = {3}
        ///AND contrato = {4}
        ///
        ///UPDATE m1.Contrato
        ///SET Situacao = 5
        ///WHERE Codigo = {5}.
        /// </summary>
        internal static string UpdateBoletoSynergius {
            get {
                return ResourceManager.GetString("UpdateBoletoSynergius", resourceCulture);
            }
        }
    }
}
